# Generated by Django 4.2.4 on 2023-08-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user_bank_account'),
        ),
        migrations.AlterField(
            model_name='usercardhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
