# Generated by Django 4.2.4 on 2023-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_user_alter_usercardhistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('YEN', 'YEN'), ('AZN', 'AZN'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('AZN', 'AZN')], default='USD', max_length=4),
        ),
        migrations.AddField(
            model_name='usercard',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='usercard',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=20),
        ),
    ]
