# Generated by Django 4.2.4 on 2023-08-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='card_balance',
            new_name='balance',
        ),
    ]
