# Generated by Django 4.2.4 on 2023-08-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_card_balance_useraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
