# Generated by Django 4.2.4 on 2023-08-10 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_is_active_alter_usercard_card_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=2, default=1000.0, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('YEN', 'YEN'), ('AZN', 'AZN'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('AZN', 'AZN')], default='USD', max_length=4)),
                ('debt', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('duration_months', models.IntegerField(default=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
