# Generated by Django 4.2.4 on 2023-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Approved', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('YEN', 'YEN'), ('AZN', 'AZN'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('AZN', 'AZN')], default='USD', max_length=4)),
            ],
        ),
    ]
