# Generated by Django 4.2.3 on 2023-08-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_documents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercardhistory",
            old_name="created",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="usercardhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "DEBIT"),
                    ("TRANSFER", "TRANSFER"),
                    ("WITHDRAWAL", "WITHDRAWAL"),
                    ("MOBILE_TOP_UP", "MOBILE_TOP_UP"),
                    ("DEPOSIT", "DEPOSIT"),
                ],
                default="DEBIT",
                max_length=50,
            ),
        ),
    ]
