# Generated by Django 4.2.3 on 2023-08-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_rename_created_usercardhistory_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercardhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
