# Generated by Django 4.2.3 on 2023-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_usercardhistory_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercardhistory",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("GBP", "GBP"),
                    ("YEN", "YEN"),
                    ("AZN", "AZN"),
                    ("EUR", "EUR"),
                    ("RUB", "RUB"),
                    ("AZN", "AZN"),
                ],
                default="USD",
                max_length=4,
            ),
        ),
    ]
