# Generated by Django 4.2.3 on 2023-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_usercardhistory_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercardhistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
