# Generated by Django 4.2.3 on 2023-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_credits_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="account_number",
            field=models.CharField(max_length=20),
        ),
    ]
